### ISSUE TITLE
为什么右下角的字数统计没了

### ISSUE THREAD

**Issue by Explorer-Dong** [HappySimple/Typora-theme-Happysimple#11]
![image](https://github.com/HappySimple/Typora-theme-Happysimple/assets/128051718/c7f55512-7266-4832-bf9c-0ae79abae585)

**Comment by HappySimple** [comment]
嗯哼？有的呀！我是Win10专业版 + Typora 1.6.7，鼠标悬浮在右下角时会比较明显！

**Comment by Explorer-Dong** [comment]
忘记打开“显示状态栏”了:laughing:
