### ISSUE TITLE
在无序列表中的引用块中不能使用有序列表

### ISSUE THREAD

**Issue by RanPIKAQ** [HappySimple/Typora-theme-Happysimple#16]
如下，块引用中输入有序列表就变成了无序列表格式。
<img width="407" alt="error" src="https://github.com/HappySimple/Typora-theme-Happysimple/assets/66256547/ca3b5559-140e-4268-8c5d-6d618ca1c4fa">

下图是typora的github主题的正确显示。
<img width="446" alt="right" src="https://github.com/HappySimple/Typora-theme-Happysimple/assets/66256547/56cf4720-562a-463d-a9fc-33e4ba203275">

@HappySimple 开心同学有空帮忙看看呗，还有之前那个引用块不能加粗显示 #14 。真的感觉这个主题做的视觉观感很好，要是这些小bug能解决就更好了，感谢！

**Comment by HappySimple** [comment]
1. 列表的显示问题已经修复；
2. 引用块的加粗显示问题是字体导致的，我更换了默认字体，现已正常显示。

**Comment by RanPIKAQ** [comment]
> 1. 列表的显示问题已经修复；
> 2. 引用块的加粗显示问题是字体导致的，我更换了默认字体，现已正常显示。

非常感谢！
