### ISSUE TITLE
有序列表和无需列表混用时会出现列表缩进无法使用的情况

### ISSUE THREAD

**Issue by shuqiang0** [HappySimple/Typora-theme-Happysimple#18]
正常情况下是这样：
![image](https://github.com/HappySimple/Typora-theme-Happysimple/assets/50195724/038fa57f-2b1c-43b2-a10f-94f09cb8b493)
使用happy simple主题下是这样：
![image](https://github.com/HappySimple/Typora-theme-Happysimple/assets/50195724/0d435c41-1f32-4f79-a689-de79ff0b2bf9)
且列表缩进会失效或者是缩进其他行。

**Comment by shuqiang0** [comment]
挺喜欢你的主题的

**Comment by HappySimple** [comment]
最新版本已修复此问题，请从代码仓库下载（暂时未发布 Releases ！）

**Comment by HappySimple** [comment]
Releases V1.0.3 已修复此问题，感谢反馈！
