### ISSUE TITLE
图片插入显示有问题

### ISSUE THREAD

**Issue by allinu** [HappySimple/Typora-theme-Happysimple#2]
- 使用md语法和img标签插入图片，图片不显示，只显示一个横线

<img width="732" alt="image" src="https://github.com/HappySimple/Typora-theme-Happysimple/assets/32992109/a6c046ac-d420-4a15-a9d1-edf0c556d562">

<img width="1105" alt="image" src="https://github.com/HappySimple/Typora-theme-Happysimple/assets/32992109/1186bae8-79cc-42f0-9e47-4dec33788f7b">

**Comment by HappySimple** [comment]
已知mac系统下存在此问题，有时间修复！（Windows系统下正常）
