### ISSUE TITLE
修改主题，增加各级小标题前置图案问题

### ISSUE THREAD

**Issue by hb-studying** [HappySimple/Typora-theme-Happysimple#20]
我自己修改了主题，让h4-h6小标题前都有图案，但是为啥h1-h3，用ctrl + 不换行，就可以直接显示图案，我新设置的h4-h6，就需要换行后才能显示呢？  请教一下，是在哪块修改的。
如图，test，用ctrl + 没换行就没法显示， test2，用ctrl + 未换行就直接显示图案了
![image](https://github.com/HappySimple/Typora-theme-Happysimple/assets/79969464/d516925f-2f4c-496b-916a-948be6b6df8b)
![image](https://github.com/HappySimple/Typora-theme-Happysimple/assets/79969464/b52c929e-d3a5-4f80-9d29-6ef419bd5e44)

**Comment by HappySimple** [comment]
我只设置了h1-h3，你可以参考源码（happysimple-set.css）增加h4-h6，后面我有空了也会优化此项~
