### ISSUE TITLE
字体无法加粗显示

### ISSUE THREAD

**Issue by ZeyuZuo** [HappySimple/Typora-theme-Happysimple#21]
这是源码

\## 进程
\### 概念
\> 程序：是\*\*静态的\*\*，是存放在
</br></br>
github主题显示
<img width="184" alt="issue1" src="https://github.com/HappySimple/Typora-theme-Happysimple/assets/93074876/641b6cc8-348a-4f5c-92ae-2eace6f6796d">
</br></br>
刚刚切换到happysimple的瞬间显示
<img width="190" alt="issue2" src="https://github.com/HappySimple/Typora-theme-Happysimple/assets/93074876/9a792207-9dde-4e1c-a079-494aa99408ff">
</br></br>
然后显示
<img width="218" alt="issue3" src="https://github.com/HappySimple/Typora-theme-Happysimple/assets/93074876/dbd84faa-67c6-4733-b0e5-598b4c565f08">

很喜欢你的主题！

**Comment by HappySimple** [comment]
最新版本已解决此问题，请从代码仓库下载（暂未发布 Releases !）
