### ISSUE TITLE
Mac系统下，图片无法显示

### ISSUE THREAD

**Issue by GEMLittleY** [HappySimple/Typora-theme-Happysimple#4]
Mac系统下，插入的图片无法显示，只有一个很小的黑线。

**Comment by HappySimple** [comment]
最新版本已修复此问题：fixed #issues 2

**Comment by GEMLittleY** [comment]
1.0.2吗？我看Release就这俩版本，然并卵，并没有修复啊。
<img width="605" alt="image" src="https://github.com/HappySimple/Typora-theme-Happysimple/assets/5027252/2ab423c2-a1b6-4f4f-9976-a00ba076055d">

**Comment by HappySimple** [comment]
请从代码仓库下载，目前未发布“Release”.

**Comment by GEMLittleY** [comment]
OKOK

**Comment by GEMLittleY** [comment]
好了，牛牛牛👍🏻
