### ISSUE TITLE
不会三线表的操作

### ISSUE THREAD

**Issue by Explorer-Dong** [HappySimple/Typora-theme-Happysimple#9]
三线表怎么渲染出来呀:cry:

**Comment by HappySimple** [comment]
demo.md中有示例！

**Comment by Explorer-Dong** [comment]
## 原来是看`Code`，一直在看`Preview` :innocent:
![image](https://github.com/HappySimple/Typora-theme-Happysimple/assets/128051718/5ffa7111-9f0f-46bb-a8fb-fddc26169f2f)
